name 'repo-server'
maintainer 'Bill Meyer'
maintainer_email 'bill@chef.io'
license 'all_rights'
description 'Installs/Configures repo-server'
long_description 'Installs/Configures repo-server'
version '0.1.16'
